### ISSUE TITLE
Make .dev and .foo forcing https optional

### ISSUE THREAD

**Issue by MurKit** [chromium/hstspreload.org#138]
With recent changes in v63 I cannot longer access virtual hosts with .dev domain.

This should be optional, right? I don't care if it's a valid TLD or not.
I don't want to use .test
Or how can I go around this? 

Maybe I can edit preload lists?
{ "name": "dev", "include_subdomains": true, "mode": "force-https" },
{ "name": "foo", "include_subdomains": true, "mode": "force-https" },

**Comment by CydeWeys** [comment]
The ideal situation is to use a real domain name that you actually own.  Since you own it, you are in charge of whether or not it appears on the HSTS preload list.  If you have a bunch of different development environments, you can spin them all up as separate subdomains of that domain.  Even better, you can configure DNS to point to the loopback address and then have it work for you without needing to hack up /etc/hosts files.

You are having these problems because .dev and .foo are actual real TLDs that do resolve globally on the Internet, and that will have an increasing number of real sites being hosted on them.  Thus you do actually care that they are valid TLDs -- because since you don't own them, breaking changes can happen to them that are outside of your control, whether that's being added to the HSTS preload list or name collisions with actual real domain names.

For more information on why we're adopting TLD-wide HSTS preloading, please see: https://security.googleblog.com/2017/09/broadening-hsts-to-secure-more-of-web.html

**Comment by lgarron** [comment]
This is not the right place for a bug like this. You can file a Chromium bug, but it will be closed with the same reasoning @CydeWeys provided here.
