### ISSUE TITLE
Misleading results for subdomains and preloaded TLDs

### ISSUE THREAD

**Issue by ericlaw1979** [chromium/hstspreload.org#143]
Repro: 
1. Visit hstspreload.org
2. Enter blog.google and hit Enter

Expect:
This domain is preloaded

Actual:
Claims it's not preloaded.

This was recently fixed in the HSTSPreload API, but that change doesn't impact the website. Discussion of this limitation is here: https://github.com/chromium/hstspreload/pull/102#issuecomment-353184441

**Comment by ericlaw1979** [comment]
The same issue can be seen if you query a subdomain of a preloaded eTLD+1, e.g. `Status: www.bayden.com is not preloaded.` despite the fact that "bayden.com" is preloaded.

**Comment by ericlaw1979** [comment]
As a hacky workaround, I suppose we could just issue more queries; dropping one leading TLD label each time.

**Comment by lgarron** [comment]
https://github.com/chromium/hstspreload.org/issues/52 / https://github.com/chromium/hstspreload/issues/85 ?

**Comment by ericlaw1979** [comment]
The change to hstspreload didn't seem to impact hstspreload.org. I haven't yet dug into why that is.

**Comment by jianglai** [comment]
The change to hstspreload API doesn't fix the problem on hstspreload.org because the website does not use the API :-D

As I stated on https://github.com/chromium/hstspreload/pull/102#issuecomment-353184441, the website uses its own cache of domain states stored in datastore, supposedly to avoid loading the preload list in each request.

**Comment by ExE-Boss** [comment]
This has now been fixed by #145
