### ISSUE TITLE
False-positive for site loading over http

### ISSUE THREAD

**Issue by Ned-Flanders** [chromium/hstspreload.org#172]
Hi there,

I'm trying to check if my site is loading with HTLS

My site is https://stormtxconference2019.com loads over https but hstspreload.org is saying the site loads over http. I've used an SSL plugin on WordPress and used a couple of other sites to check the site is fully loading over https and it is, one of the sites also checked that it's loading with HSTS and that was successful.

I wasn't sure if this was an error on my end or yours, possibly because the site isn't loading with www.?

Thanks

![image](https://user-images.githubusercontent.com/6885462/53482517-4682b080-3a77-11e9-83cf-36963abf1524.png)

**Comment by nharper** [comment]
Looking at https://hstspreload.org/?domain=stormtxconference2019.com, I see 1 error and 1 warning. The error is that the max-age is too low (300 seconds), and the warning is that the HSTS header is being sent over HTTP (instead of just HSTS). The only case where the www subdomain matters is that if there's a DNS record for it, it must support HTTPS. Otherwise, all tests are performed on the root domain.

This issue tracker is for development of the hstspreload.org website itself, not for questions about preloading a specific domain. If you have more questions, please email hstspreload@chromium.org, and I'll reply there.
