### ISSUE TITLE
An error I cannot understand when submitting the domain travellings.cn

### ISSUE THREAD

**Issue by linlinzzo** [chromium/hstspreload.org#212]
English is not my native language; please excuse typing errors.

When I submitted the domain travellings.cn, an error message appeared.

Error: www subdomain does not support HTTPS
Domain error: The www subdomain exists, but we couldn't connect to it using HTTPS ("remote error: tls: unrecognized name"). Since many people type this by habit, HSTS preloading would likely cause issues for your site.

![image](https://user-images.githubusercontent.com/79007796/215318344-b0aea1f1-2e47-45cb-a859-f5d3b6461ca3.png)

I searched the key word "unrecognized name" but the result was too difficult to understand and couldn't let me resolve the issue. I find that the HTTPS state of www.travellings.cn is normal using Chrome and Edge.

How can I resolve this issue?

**Comment by nharper** [comment]
This error meant that when hstspreload.org attempted to connect to www.travellings.cn, it was unable to establish a TLS connection. Specifically, the connection failed because the certificate presented by the server was not valid for the domain name www.travellings.cn.

I notice that this error does not appear for your domain any more, so I assume you have resolved this issue.
